# Generated by Django 5.0.10 on 2026-02-24 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('title', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('type', models.CharField(choices=[('legal', 'Prazo Legal'), ('hearing', 'Audiência'), ('meeting', 'Reunião'), ('task', 'Tarefa'), ('other', 'Outro')], default='legal', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluído'), ('overdue', 'Vencido'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Prazo',
                'verbose_name_plural': 'Prazos',
            },
        ),
    ]
