# Generated by Django 5.0.10 on 2026-02-24 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deadlines', '0002_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organização'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='deadline',
            index=models.Index(fields=['organization', 'office', 'due_date'], name='deadlines_d_organiz_3b1a3e_idx'),
        ),
        migrations.AddIndex(
            model_name='deadline',
            index=models.Index(fields=['organization', 'office', 'status'], name='deadlines_d_organiz_3188a1_idx'),
        ),
    ]
