# Generated by Django 5.0.10 on 2026-02-26 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offices', '0002_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('module', models.CharField(choices=[('auth', 'Autenticação'), ('processes', 'Processos'), ('deadlines', 'Prazos'), ('customers', 'Contatos'), ('documents', 'Documentos'), ('finance', 'Financeiro'), ('tasks', 'Tarefas'), ('kanban', 'Kanban'), ('calendar', 'Agenda'), ('team', 'Equipe'), ('settings', 'Configurações'), ('system', 'Sistema')], max_length=32)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('password_changed', 'Senha alterada'), ('created', 'Criado'), ('updated', 'Atualizado'), ('deleted', 'Excluído'), ('restored', 'Restaurado'), ('status_changed', 'Status alterado'), ('assigned', 'Atribuído'), ('commented', 'Comentou'), ('uploaded', 'Upload'), ('downloaded', 'Download'), ('exported', 'Exportado'), ('moved', 'Movido'), ('completed', 'Concluído'), ('reopened', 'Reaberto'), ('member_added', 'Membro adicionado'), ('member_removed', 'Membro removido'), ('role_changed', 'Função alterada'), ('permission_changed', 'Permissão alterada')], max_length=32)),
                ('entity_type', models.CharField(blank=True, max_length=100)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('entity_label', models.CharField(blank=True, max_length=255)),
                ('summary', models.CharField(max_length=500)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='offices.office')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Evento de Atividade',
                'verbose_name_plural': 'Eventos de Atividade',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='activity_ac_organiz_ed03fe_idx'), models.Index(fields=['organization', 'office', 'created_at'], name='activity_ac_organiz_99032e_idx'), models.Index(fields=['organization', 'module', 'created_at'], name='activity_ac_organiz_44ddef_idx'), models.Index(fields=['organization', 'action', 'created_at'], name='activity_ac_organiz_79b7e7_idx'), models.Index(fields=['organization', 'actor', 'created_at'], name='activity_ac_organiz_e53d85_idx'), models.Index(fields=['organization', 'entity_type', 'entity_id'], name='activity_ac_organiz_16b61e_idx')],
            },
        ),
    ]
