# Generated by Django 5.0.10 on 2026-02-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('password_changed', 'Senha alterada'), ('created', 'Criado'), ('updated', 'Atualizado'), ('deleted', 'Excluído'), ('restored', 'Restaurado'), ('status_changed', 'Status alterado'), ('assigned', 'Atribuído'), ('commented', 'Comentou'), ('uploaded', 'Upload'), ('downloaded', 'Download'), ('exported', 'Exportado'), ('moved', 'Movido'), ('completed', 'Concluído'), ('reopened', 'Reaberto'), ('member_added', 'Membro adicionado'), ('member_removed', 'Membro removido'), ('role_changed', 'Função alterada'), ('permission_changed', 'Permissão alterada'), ('custom', 'Custom')], max_length=32),
        ),
    ]
