# Generated by Django 5.0.10 on 2026-02-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deletado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome/Razão Social')),
                ('document', models.CharField(blank=True, help_text='CPF (11 dígitos) ou CNPJ (14 dígitos)', max_length=50, verbose_name='CPF/CNPJ')),
                ('type', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('prospect', 'Prospect'), ('client', 'Cliente'), ('inactive', 'Inativo'), ('archived', 'Arquivado')], default='lead', max_length=20, verbose_name='Status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='Formato: (XX) XXXXX-XXXX', max_length=40, verbose_name='Telefone')),
                ('phone_secondary', models.CharField(blank=True, max_length=40, verbose_name='Telefone Secundário')),
                ('whatsapp', models.CharField(blank=True, max_length=40, verbose_name='WhatsApp')),
                ('address_street', models.CharField(blank=True, max_length=255, verbose_name='Rua')),
                ('address_number', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('address_complement', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('address_neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('address_city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('address_state', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('address_zipcode', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='Profissão')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('nationality', models.CharField(blank=True, default='Brasileira', max_length=50, verbose_name='Nacionalidade')),
                ('marital_status', models.CharField(blank=True, max_length=50, verbose_name='Estado Civil')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Nome Fantasia')),
                ('state_registration', models.CharField(blank=True, max_length=50, verbose_name='Inscrição Estadual')),
                ('municipal_registration', models.CharField(blank=True, max_length=50, verbose_name='Inscrição Municipal')),
                ('origin', models.CharField(choices=[('website', 'Website'), ('referral', 'Indicação'), ('social_media', 'Redes Sociais'), ('advertising', 'Publicidade'), ('event', 'Evento'), ('partner', 'Parceiro'), ('other', 'Outro')], default='other', max_length=50, verbose_name='Origem')),
                ('referral_name', models.CharField(blank=True, max_length=255, verbose_name='Nome do Indicador')),
                ('tags', models.CharField(blank=True, help_text='Tags separadas por vírgula (ex: vip, urgente, trabalhista)', max_length=500, verbose_name='Tags')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('internal_notes', models.TextField(blank=True, help_text='Notas visíveis apenas internamente', verbose_name='Notas Internas')),
                ('first_contact_date', models.DateField(blank=True, null=True, verbose_name='Data do Primeiro Contato')),
                ('last_interaction_date', models.DateField(blank=True, null=True, verbose_name='Última Interação')),
                ('pipeline_stage', models.CharField(blank=True, choices=[('novo', 'Novo'), ('contato_feito', 'Contato Feito'), ('reuniao_marcada', 'Reunião Marcada'), ('proposta_enviada', 'Proposta Enviada'), ('em_negociacao', 'Em Negociação'), ('ganho', 'Ganho'), ('perdido', 'Perdido')], max_length=30, verbose_name='Etapa do Funil')),
                ('next_action', models.CharField(blank=True, max_length=500, verbose_name='Próxima Ação')),
                ('next_action_date', models.DateField(blank=True, null=True, verbose_name='Data da Próxima Ação')),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, help_text='Previsão de honorários ou valor de causa', max_digits=12, null=True, verbose_name='Valor Estimado (R$)')),
                ('loss_reason', models.CharField(blank=True, max_length=500, verbose_name='Motivo da Perda')),
                ('can_whatsapp', models.BooleanField(default=True, verbose_name='Aceita WhatsApp')),
                ('can_email', models.BooleanField(default=True, verbose_name='Aceita Email')),
                ('lgpd_consent_date', models.DateField(blank=True, null=True, verbose_name='Data do Consentimento LGPD')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('type', models.CharField(choices=[('cpf', 'CPF'), ('rg', 'RG'), ('cnpj', 'CNPJ'), ('contract', 'Contrato'), ('power_of_attorney', 'Procuração'), ('proof_of_address', 'Comprovante de Endereço'), ('other', 'Outro')], default='other', max_length=50, verbose_name='Tipo')),
                ('file', models.FileField(upload_to='customer_documents/', verbose_name='Arquivo')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Documento do Contato',
                'verbose_name_plural': 'Documentos do Contato',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('type', models.CharField(choices=[('call', 'Ligação'), ('email', 'Email'), ('meeting', 'Reunião'), ('whatsapp', 'WhatsApp'), ('visit', 'Visita'), ('note', 'Nota'), ('other', 'Outro')], default='note', max_length=20, verbose_name='Tipo')),
                ('date', models.DateTimeField(verbose_name='Data/Hora')),
                ('subject', models.CharField(max_length=255, verbose_name='Assunto')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Interação',
                'verbose_name_plural': 'Interações',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CustomerRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('socio', 'Sócio(a)'), ('representante', 'Representante Legal'), ('conjuge', 'Cônjuge'), ('dependente', 'Dependente'), ('testemunha', 'Testemunha'), ('indicador', 'Indicador'), ('outro', 'Outro')], max_length=30, verbose_name='Tipo de Relação')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Relacionamento',
                'verbose_name_plural': 'Relacionamentos',
            },
        ),
    ]
