# Generated by Django 5.0.10 on 2026-02-22 12:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('offices', '0001_initial'),
        ('organizations', '0001_initial'),
        ('processes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('billing_type', models.CharField(choices=[('one_time', 'Pagamento Único'), ('monthly', 'Mensal'), ('success_fee', 'Êxito'), ('hourly', 'Por Hora'), ('installments', 'Parcelado')], default='one_time', max_length=20, verbose_name='Tipo de Cobrança')),
                ('installments', models.PositiveIntegerField(default=1, help_text="Número de parcelas (para tipo 'Parcelado')", verbose_name='Parcelas')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativo'), ('suspended', 'Suspenso'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_agreements', to='customers.customer', verbose_name='Cliente')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='offices.office', verbose_name='Escritório')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organização')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_agreements', to='processes.process', verbose_name='Processo')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_agreements', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Contrato de Honorários',
                'verbose_name_plural': 'Contratos de Honorários',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('number', models.CharField(blank=True, help_text='Número da fatura (ex: 2024/001)', max_length=50, null=True, verbose_name='Número')),
                ('issue_date', models.DateField(verbose_name='Data de Emissão')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Desconto')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('issued', 'Emitida'), ('sent', 'Enviada'), ('paid', 'Paga'), ('overdue', 'Vencida'), ('cancelled', 'Cancelada')], default='draft', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Método de Pagamento')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='finance.feeagreement', verbose_name='Contrato')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='offices.office', verbose_name='Escritório')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('paid_at', models.DateField(verbose_name='Data do Pagamento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('method', models.CharField(choices=[('pix', 'PIX'), ('bank_transfer', 'Transferência Bancária'), ('debit_card', 'Cartão de Débito'), ('credit_card', 'Cartão de Crédito'), ('cash', 'Dinheiro'), ('check', 'Cheque'), ('boleto', 'Boleto'), ('other', 'Outro')], default='pix', max_length=30, verbose_name='Método')),
                ('reference', models.CharField(blank=True, help_text='Número do comprovante, transação, etc', max_length=255, verbose_name='Referência')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.invoice', verbose_name='Fatura')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='offices.office', verbose_name='Escritório')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organização')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_recorded', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Escopo / Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Total')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('sent', 'Enviada'), ('accepted', 'Aceita'), ('rejected', 'Rejeitada'), ('expired', 'Expirada')], default='draft', max_length=20, verbose_name='Status')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Válida até')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='proposals/', verbose_name='PDF')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='customers.customer', verbose_name='Cliente')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='offices.office', verbose_name='Escritório')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organização')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='processes.process', verbose_name='Processo')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('category', models.CharField(choices=[('salary', 'Salários'), ('rent', 'Aluguel'), ('utilities', 'Contas (água, luz, etc)'), ('supplies', 'Material de Escritório'), ('technology', 'Tecnologia/Software'), ('marketing', 'Marketing'), ('legal_fees', 'Taxas Judiciais'), ('travel', 'Viagens'), ('training', 'Treinamentos'), ('consulting', 'Consultoria'), ('other', 'Outros')], default='other', max_length=50, verbose_name='Categoria')),
                ('date', models.DateField(verbose_name='Data')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Paga'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Status')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Método de Pagamento')),
                ('supplier', models.CharField(blank=True, max_length=255, verbose_name='Fornecedor')),
                ('reference', models.CharField(blank=True, help_text='Número da nota fiscal, comprovante, etc', max_length=255, verbose_name='Referência')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='offices.office', verbose_name='Escritório')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organização')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['organization', 'office', 'date'], name='finance_exp_organiz_f6c52a_idx'), models.Index(fields=['organization', 'office', 'status'], name='finance_exp_organiz_4b4382_idx'), models.Index(fields=['category', 'date'], name='finance_exp_categor_576c9a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='feeagreement',
            index=models.Index(fields=['organization', 'office', 'status'], name='finance_fee_organiz_53649e_idx'),
        ),
        migrations.AddIndex(
            model_name='feeagreement',
            index=models.Index(fields=['customer', 'status'], name='finance_fee_custome_a080d1_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'office', 'status'], name='finance_inv_organiz_32bb69_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['agreement', 'status'], name='finance_inv_agreeme_973890_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='finance_inv_due_dat_b93853_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('organization', 'office', 'number')},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['organization', 'office', 'paid_at'], name='finance_pay_organiz_4c0261_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice'], name='finance_pay_invoice_122c17_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['organization', 'office', 'status'], name='finance_pro_organiz_a28cb8_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['customer', 'status'], name='finance_pro_custome_73ccb2_idx'),
        ),
    ]
