# Generated by Django 5.0.10 on 2026-02-24 13:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('category', models.CharField(choices=[('salary', 'Salários'), ('rent', 'Aluguel'), ('utilities', 'Contas (água, luz, etc)'), ('supplies', 'Material de Escritório'), ('technology', 'Tecnologia/Software'), ('marketing', 'Marketing'), ('legal_fees', 'Taxas Judiciais'), ('travel', 'Viagens'), ('training', 'Treinamentos'), ('consulting', 'Consultoria'), ('other', 'Outros')], default='other', max_length=50, verbose_name='Categoria')),
                ('date', models.DateField(verbose_name='Data')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Paga'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Status')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Método de Pagamento')),
                ('supplier', models.CharField(blank=True, max_length=255, verbose_name='Fornecedor')),
                ('reference', models.CharField(blank=True, help_text='Número da nota fiscal, comprovante, etc', max_length=255, verbose_name='Referência')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FeeAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('billing_type', models.CharField(choices=[('one_time', 'Pagamento Único'), ('monthly', 'Mensal'), ('success_fee', 'Êxito'), ('hourly', 'Por Hora'), ('installments', 'Parcelado')], default='one_time', max_length=20, verbose_name='Tipo de Cobrança')),
                ('installments', models.PositiveIntegerField(default=1, help_text="Número de parcelas (para tipo 'Parcelado')", verbose_name='Parcelas')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativo'), ('suspended', 'Suspenso'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Contrato de Honorários',
                'verbose_name_plural': 'Contratos de Honorários',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('number', models.CharField(blank=True, help_text='Número da fatura (ex: 2024/001)', max_length=50, null=True, verbose_name='Número')),
                ('issue_date', models.DateField(verbose_name='Data de Emissão')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Desconto')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('issued', 'Emitida'), ('sent', 'Enviada'), ('paid', 'Paga'), ('overdue', 'Vencida'), ('cancelled', 'Cancelada')], default='draft', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Método de Pagamento')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('paid_at', models.DateField(verbose_name='Data do Pagamento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('method', models.CharField(choices=[('pix', 'PIX'), ('bank_transfer', 'Transferência Bancária'), ('debit_card', 'Cartão de Débito'), ('credit_card', 'Cartão de Crédito'), ('cash', 'Dinheiro'), ('check', 'Cheque'), ('boleto', 'Boleto'), ('other', 'Outro')], default='pix', max_length=30, verbose_name='Método')),
                ('reference', models.CharField(blank=True, help_text='Número do comprovante, transação, etc', max_length=255, verbose_name='Referência')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Escopo / Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Total')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('sent', 'Enviada'), ('accepted', 'Aceita'), ('rejected', 'Rejeitada'), ('expired', 'Expirada')], default='draft', max_length=20, verbose_name='Status')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Válida até')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='proposals/', verbose_name='PDF')),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
                'ordering': ['-created_at'],
            },
        ),
    ]
