# Generated by Django 5.0.10 on 2026-02-24 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_initial'),
        ('finance', '0002_initial'),
        ('offices', '0001_initial'),
        ('organizations', '0001_initial'),
        ('processes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organização'),
        ),
        migrations.AddField(
            model_name='expense',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='feeagreement',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_agreements', to='customers.customer', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='feeagreement',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='offices.office', verbose_name='Escritório'),
        ),
        migrations.AddField(
            model_name='feeagreement',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organização'),
        ),
        migrations.AddField(
            model_name='feeagreement',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_agreements', to='processes.process', verbose_name='Processo'),
        ),
        migrations.AddField(
            model_name='feeagreement',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_agreements', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='finance.feeagreement', verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='offices.office', verbose_name='Escritório'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organização'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.invoice', verbose_name='Fatura'),
        ),
        migrations.AddField(
            model_name='payment',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='offices.office', verbose_name='Escritório'),
        ),
        migrations.AddField(
            model_name='payment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organização'),
        ),
        migrations.AddField(
            model_name='payment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_recorded', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='customers.customer', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='offices.office', verbose_name='Escritório'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organização'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='processes.process', verbose_name='Processo'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['organization', 'office', 'date'], name='finance_exp_organiz_f6c52a_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['organization', 'office', 'status'], name='finance_exp_organiz_4b4382_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category', 'date'], name='finance_exp_categor_576c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='feeagreement',
            index=models.Index(fields=['organization', 'office', 'status'], name='finance_fee_organiz_53649e_idx'),
        ),
        migrations.AddIndex(
            model_name='feeagreement',
            index=models.Index(fields=['customer', 'status'], name='finance_fee_custome_a080d1_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'office', 'status'], name='finance_inv_organiz_32bb69_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['agreement', 'status'], name='finance_inv_agreeme_973890_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='finance_inv_due_dat_b93853_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('organization', 'office', 'number')},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['organization', 'office', 'paid_at'], name='finance_pay_organiz_4c0261_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice'], name='finance_pay_invoice_122c17_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['organization', 'office', 'status'], name='finance_pro_organiz_a28cb8_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['customer', 'status'], name='finance_pro_custome_73ccb2_idx'),
        ),
    ]
