# Generated by Django 5.0.10 on 2026-02-24 13:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deadlines', '0002_initial'),
        ('offices', '0001_initial'),
        ('organizations', '0001_initial'),
        ('processes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('source', models.CharField(choices=[('djen', 'DJEN - Diário Eletrônico Nacional'), ('datajud', 'Datajud (enriquecimento)'), ('manual', 'Importação Manual'), ('tjsp', 'TJSP - Tribunal de Justiça de SP'), ('tjrj', 'TJRJ - Tribunal de Justiça do RJ'), ('other', 'Outro')], default='manual', max_length=20, verbose_name='Fonte')),
                ('source_id', models.CharField(blank=True, help_text='ID único da fonte externa', max_length=255, verbose_name='ID na Fonte')),
                ('raw_text', models.TextField(help_text='Texto completo da publicação', verbose_name='Texto Bruto')),
                ('content_hash', models.CharField(help_text='SHA256 do conteúdo para idempotência', max_length=64, unique=True, verbose_name='Hash')),
                ('publication_date', models.DateField(help_text='Data oficial da publicação no diário', verbose_name='Data da Publicação')),
                ('import_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Importação')),
                ('process_cnj', models.CharField(blank=True, db_index=True, help_text='Número CNJ extraído da publicação', max_length=40, verbose_name='Número CNJ')),
                ('original_file', models.FileField(blank=True, help_text='PDF ou arquivo original da publicação', null=True, upload_to='publications/%Y/%m/', verbose_name='Arquivo Original')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Dados adicionais da fonte (tribunal, órgão, etc)', verbose_name='Metadados')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications_imported', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='offices.office', verbose_name='Escritório')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Publicação Oficial',
                'verbose_name_plural': 'Publicações Oficiais',
                'ordering': ['-publication_date', '-import_date'],
            },
        ),
        migrations.CreateModel(
            name='JudicialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('event_type', models.CharField(choices=[('citacao', 'Citação'), ('intimacao', 'Intimação'), ('sentenca', 'Sentença'), ('acordao', 'Acórdão'), ('decisao', 'Decisão Interlocutória'), ('despacho', 'Despacho'), ('edital', 'Edital'), ('other', 'Outro')], max_length=20, verbose_name='Tipo de Evento')),
                ('status', models.CharField(choices=[('new', 'Nova'), ('assigned', 'Atribuída'), ('in_progress', 'Em Andamento'), ('resolved', 'Resolvida'), ('archived', 'Arquivada')], default='new', max_length=20, verbose_name='Status')),
                ('urgency', models.CharField(choices=[('critical', 'Crítica'), ('urgent', 'Urgente'), ('normal', 'Normal')], default='normal', max_length=20, verbose_name='Urgência')),
                ('notes', models.TextField(blank=True, verbose_name='Observações Internas')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Atribuído em')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_events', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('deadline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judicial_events', to='deadlines.deadline', verbose_name='Prazo Derivado')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='offices.office', verbose_name='Escritório')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organização')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judicial_events', to='processes.process', verbose_name='Processo Vinculado')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='publications.publication', verbose_name='Publicação Oficial')),
            ],
            options={
                'verbose_name': 'Evento Jurídico',
                'verbose_name_plural': 'Eventos Jurídicos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicationFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('filter_type', models.CharField(choices=[('cnj', 'Número CNJ'), ('oab', 'OAB'), ('cpf', 'CPF'), ('cnpj', 'CNPJ'), ('keyword', 'Palavra-chave (auxiliar)')], max_length=20, verbose_name='Tipo')),
                ('value', models.CharField(max_length=255, verbose_name='Valor')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('case_sensitive', models.BooleanField(default=False, verbose_name='Case Sensitive')),
                ('match_count', models.PositiveIntegerField(default=0, verbose_name='Matches')),
                ('last_matched_at', models.DateTimeField(blank=True, null=True, verbose_name='Último Match')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='offices.office', verbose_name='Escritório')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Filtro de Publicação',
                'verbose_name_plural': 'Filtros de Publicações',
                'ordering': ['filter_type', 'value'],
            },
        ),
        migrations.CreateModel(
            name='PublicationImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('source', models.CharField(choices=[('djen', 'DJEN - Diário Eletrônico Nacional'), ('datajud', 'Datajud (enriquecimento)'), ('manual', 'Importação Manual'), ('tjsp', 'TJSP - Tribunal de Justiça de SP'), ('tjrj', 'TJRJ - Tribunal de Justiça do RJ'), ('other', 'Outro')], max_length=20, verbose_name='Fonte')),
                ('status', models.CharField(choices=[('processing', 'Processando'), ('success', 'Sucesso'), ('partial', 'Parcial (com erros)'), ('failed', 'Falhou')], default='processing', max_length=20, verbose_name='Status')),
                ('total_found', models.PositiveIntegerField(default=0, verbose_name='Total Encontrado')),
                ('total_imported', models.PositiveIntegerField(default=0, verbose_name='Total Importado')),
                ('total_duplicates', models.PositiveIntegerField(default=0, verbose_name='Duplicados (ignorados)')),
                ('total_errors', models.PositiveIntegerField(default=0, verbose_name='Erros')),
                ('filters_applied', models.JSONField(blank=True, default=dict, verbose_name='Filtros Aplicados')),
                ('error_log', models.TextField(blank=True, verbose_name='Log de Erros')),
                ('summary', models.TextField(blank=True, verbose_name='Resumo')),
                ('source_file', models.FileField(blank=True, null=True, upload_to='publications/imports/%Y/%m/', verbose_name='Arquivo Fonte')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado em')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publication_imports', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='offices.office', verbose_name='Escritório')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Importação de Publicações',
                'verbose_name_plural': 'Importações de Publicações',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('event_type', models.CharField(choices=[('citacao', 'Citação'), ('intimacao', 'Intimação'), ('sentenca', 'Sentença'), ('acordao', 'Acórdão'), ('decisao', 'Decisão Interlocutória'), ('despacho', 'Despacho'), ('edital', 'Edital'), ('other', 'Outro')], max_length=20, verbose_name='Tipo de Evento')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('base_legal', models.TextField(blank=True, help_text='CPC, CLT, etc', verbose_name='Base Legal')),
                ('days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Dias')),
                ('business_days', models.BooleanField(default=True, verbose_name='Dias Úteis')),
                ('auto_create_deadline', models.BooleanField(default=True, verbose_name='Criar Prazo Automaticamente')),
                ('auto_urgency', models.CharField(choices=[('critical', 'Crítica'), ('urgent', 'Urgente'), ('normal', 'Normal')], default='normal', max_length=20, verbose_name='Urgência Automática')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Maior número = maior prioridade', verbose_name='Prioridade')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='offices.office', verbose_name='Escritório')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Regra de Prazo',
                'verbose_name_plural': 'Regras de Prazo',
                'ordering': ['-priority', 'event_type'],
            },
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['organization', 'office', 'publication_date'], name='publication_organiz_2fde0c_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['organization', 'office', 'process_cnj'], name='publication_organiz_5e73b3_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['source', 'source_id'], name='publication_source_2e775e_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['content_hash'], name='publication_content_75aaa9_idx'),
        ),
        migrations.AddIndex(
            model_name='judicialevent',
            index=models.Index(fields=['organization', 'office', 'status'], name='publication_organiz_a4ec50_idx'),
        ),
        migrations.AddIndex(
            model_name='judicialevent',
            index=models.Index(fields=['organization', 'office', 'urgency'], name='publication_organiz_d7ffed_idx'),
        ),
        migrations.AddIndex(
            model_name='judicialevent',
            index=models.Index(fields=['assigned_to', 'status'], name='publication_assigne_918e38_idx'),
        ),
        migrations.AddIndex(
            model_name='judicialevent',
            index=models.Index(fields=['process'], name='publication_process_5eb847_idx'),
        ),
        migrations.AddIndex(
            model_name='publicationfilter',
            index=models.Index(fields=['organization', 'office', 'filter_type', 'is_active'], name='publication_organiz_4d831c_idx'),
        ),
        migrations.AddIndex(
            model_name='publicationrule',
            index=models.Index(fields=['organization', 'office', 'event_type', 'is_active'], name='publication_organiz_ecd0f9_idx'),
        ),
    ]
