# Generated by Django 5.0.10 on 2026-02-26 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadlines', '0003_initial'),
        ('offices', '0002_initial'),
        ('organizations', '0001_initial'),
        ('processes', '0001_initial'),
        ('publications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('process_cnj', models.CharField(db_index=True, max_length=40, verbose_name='Número CNJ')),
                ('sources', models.JSONField(default=list, help_text='Ex: ["datajud", "comunica"]', verbose_name='Fontes de Monitoramento')),
                ('tribunal', models.CharField(blank=True, max_length=20, verbose_name='Tribunal')),
                ('tribunal_index', models.CharField(blank=True, help_text='Ex: tjsp, trf3 — usado nas queries ao DataJud', max_length=20, verbose_name='Índice DataJud')),
                ('current_phase', models.CharField(blank=True, max_length=200, verbose_name='Fase Atual')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('autocomplete_enabled', models.BooleanField(default=False, help_text='Permite que dados das APIs preencham campos do processo', verbose_name='Autocompletar Processo')),
                ('initial_sync_done', models.BooleanField(default=False, verbose_name='Sync Inicial Concluído')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronização')),
                ('sync_cursors', models.JSONField(blank=True, default=dict, help_text="Controla onde cada fonte parou (ex: {'datajud': '2026-01-15'})", verbose_name='Cursores de Sync')),
            ],
            options={
                'verbose_name': 'Monitoramento de Processo',
                'verbose_name_plural': 'Monitoramentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-publication_date', '-import_date'], 'verbose_name': 'Publicação / Andamento', 'verbose_name_plural': 'Publicações / Andamentos'},
        ),
        migrations.RemoveField(
            model_name='publicationimport',
            name='imported_by',
        ),
        migrations.AddField(
            model_name='publication',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='processes.process', verbose_name='Processo'),
        ),
        migrations.AddField(
            model_name='publicationfilter',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publication_filters', to='processes.process', verbose_name='Processo'),
        ),
        migrations.AddField(
            model_name='publicationimport',
            name='reference_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Referência'),
        ),
        migrations.AddField(
            model_name='publicationimport',
            name='total_matched',
            field=models.PositiveIntegerField(default=0, verbose_name='Vinculadas a processos'),
        ),
        migrations.AddField(
            model_name='publicationimport',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publication_imports_triggered', to=settings.AUTH_USER_MODEL, verbose_name='Disparado por'),
        ),
        migrations.AlterField(
            model_name='judicialevent',
            name='event_type',
            field=models.CharField(choices=[('citacao', 'Citação'), ('intimacao', 'Intimação'), ('sentenca', 'Sentença'), ('acordao', 'Acórdão'), ('decisao', 'Decisão Interlocutória'), ('despacho', 'Despacho'), ('juntada', 'Juntada'), ('audiencia', 'Audiência'), ('peticao', 'Petição'), ('edital', 'Edital'), ('movimento', 'Movimento Processual'), ('other', 'Outro')], default='movimento', max_length=20, verbose_name='Tipo de Evento'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='content_hash',
            field=models.CharField(help_text='SHA-256 para deduplicação automática', max_length=64, unique=True, verbose_name='Hash de Conteúdo'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadados'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='original_file',
            field=models.FileField(blank=True, null=True, upload_to='publications/%Y/%m/', verbose_name='Arquivo Original'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='process_cnj',
            field=models.CharField(blank=True, db_index=True, help_text='Extraído automaticamente do texto', max_length=40, verbose_name='Número CNJ'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_date',
            field=models.DateField(verbose_name='Data da Publicação'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='raw_text',
            field=models.TextField(help_text='Texto completo da publicação/andamento', verbose_name='Texto Bruto'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='source',
            field=models.CharField(choices=[('datajud', 'DataJud (CNJ)'), ('comunica', 'Comunica API (PJe)'), ('djen', 'DJEN — Diário Eletrônico Nacional'), ('tjsp', 'TJSP'), ('tjrj', 'TJRJ'), ('trf1', 'TRF1'), ('trf2', 'TRF2'), ('trf3', 'TRF3'), ('trf4', 'TRF4'), ('trf5', 'TRF5'), ('manual', 'Inserção Manual'), ('other', 'Outro')], default='manual', max_length=20, verbose_name='Fonte'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='source_id',
            field=models.CharField(blank=True, help_text='ID único da publicação na fonte externa (idempotência)', max_length=255, verbose_name='ID na Fonte'),
        ),
        migrations.AlterField(
            model_name='publicationfilter',
            name='filter_type',
            field=models.CharField(choices=[('cnj', 'Número CNJ'), ('oab', 'OAB'), ('cpf', 'CPF'), ('cnpj', 'CNPJ'), ('keyword', 'Palavra-chave')], max_length=20, verbose_name='Tipo de Filtro'),
        ),
        migrations.AlterField(
            model_name='publicationfilter',
            name='match_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Total de Matches'),
        ),
        migrations.AlterField(
            model_name='publicationimport',
            name='source',
            field=models.CharField(choices=[('datajud', 'DataJud (CNJ)'), ('comunica', 'Comunica API (PJe)'), ('djen', 'DJEN — Diário Eletrônico Nacional'), ('tjsp', 'TJSP'), ('tjrj', 'TJRJ'), ('trf1', 'TRF1'), ('trf2', 'TRF2'), ('trf3', 'TRF3'), ('trf4', 'TRF4'), ('trf5', 'TRF5'), ('manual', 'Inserção Manual'), ('other', 'Outro')], max_length=20, verbose_name='Fonte'),
        ),
        migrations.AlterField(
            model_name='publicationimport',
            name='total_duplicates',
            field=models.PositiveIntegerField(default=0, verbose_name='Duplicatas ignoradas'),
        ),
        migrations.AlterField(
            model_name='publicationimport',
            name='total_found',
            field=models.PositiveIntegerField(default=0, verbose_name='Encontradas'),
        ),
        migrations.AlterField(
            model_name='publicationimport',
            name='total_imported',
            field=models.PositiveIntegerField(default=0, verbose_name='Importadas'),
        ),
        migrations.AlterField(
            model_name='publicationrule',
            name='base_legal',
            field=models.TextField(blank=True, help_text='Ex: CPC art. 335 — 15 dias para contestar', verbose_name='Base Legal'),
        ),
        migrations.AlterField(
            model_name='publicationrule',
            name='event_type',
            field=models.CharField(choices=[('citacao', 'Citação'), ('intimacao', 'Intimação'), ('sentenca', 'Sentença'), ('acordao', 'Acórdão'), ('decisao', 'Decisão Interlocutória'), ('despacho', 'Despacho'), ('juntada', 'Juntada'), ('audiencia', 'Audiência'), ('peticao', 'Petição'), ('edital', 'Edital'), ('movimento', 'Movimento Processual'), ('other', 'Outro')], max_length=20, verbose_name='Tipo de Evento'),
        ),
        migrations.AlterField(
            model_name='publicationrule',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Maior número = maior prioridade quando houver múltiplas regras para o mesmo tipo', verbose_name='Prioridade'),
        ),
        migrations.AddIndex(
            model_name='judicialevent',
            index=models.Index(fields=['organization', 'office', 'event_type'], name='publication_organiz_75917b_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['organization', 'office', 'source'], name='publication_organiz_ae03c5_idx'),
        ),
        migrations.AddIndex(
            model_name='publicationfilter',
            index=models.Index(fields=['organization', 'office', 'process'], name='publication_organiz_172935_idx'),
        ),
        migrations.AddField(
            model_name='processmonitoring',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ativado por'),
        ),
        migrations.AddField(
            model_name='processmonitoring',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='offices.office', verbose_name='Escritório'),
        ),
        migrations.AddField(
            model_name='processmonitoring',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organização'),
        ),
        migrations.AddField(
            model_name='processmonitoring',
            name='process',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring', to='processes.process', verbose_name='Processo'),
        ),
    ]
