# Generated by ChatGPT on 2026-02-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0002_processmonitoring_alter_publication_options_and_more"),
    ]

    operations = [
        # Deduplicação não pode ser global: precisa respeitar (organization, office)
        migrations.AlterField(
            model_name="publication",
            name="content_hash",
            field=models.CharField(
                help_text="SHA-256 para deduplicação automática",
                max_length=64,
                verbose_name="Hash de Conteúdo",
            ),
        ),
        migrations.AddConstraint(
            model_name="publication",
            constraint=models.UniqueConstraint(
                fields=("organization", "office", "content_hash"),
                name="uniq_publication_content_hash_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="publication",
            constraint=models.UniqueConstraint(
                fields=("organization", "office", "source", "source_id"),
                condition=~models.Q(source_id=""),
                name="uniq_publication_source_id_per_tenant",
            ),
        ),
    ]
