# Generated by Django 5.0.10 on 2026-02-22 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Configurações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Escritório',
                'verbose_name_plural': 'Escritórios',
                'ordering': ('name',),
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
