# Generated by Django 5.0.10 on 2026-02-24 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offices', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='organizations.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='office',
            unique_together={('organization', 'name')},
        ),
    ]
