# Generated by Django 5.0.10 on 2026-02-22 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('color', models.CharField(blank=True, default='', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['organization', 'slug'], name='core_tag_organiz_90293e_idx')],
                'unique_together': {('organization', 'slug')},
            },
        ),
    ]
