# Generated by Django 5.0.10 on 2026-02-24 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['organization', 'slug'], name='core_tag_organiz_90293e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('organization', 'slug')},
        ),
    ]
