# Generated by Django 5.0.10 on 2026-02-22 12:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('offices', '0001_initial'),
        ('organizations', '0001_initial'),
        ('processes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('category', models.CharField(choices=[('contract', 'Contrato'), ('petition', 'Petição'), ('decision', 'Decisão/Sentença'), ('power_of_attorney', 'Procuração'), ('certificate', 'Certidão'), ('minutes', 'Ata'), ('opinion', 'Parecer'), ('appeal', 'Recurso'), ('evidence', 'Prova'), ('correspondence', 'Correspondência'), ('internal', 'Documento Interno'), ('other', 'Outro')], default='other', max_length=50, verbose_name='Categoria')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('review', 'Em Revisão'), ('approved', 'Aprovado'), ('signed', 'Assinado'), ('filed', 'Protocolado'), ('archived', 'Arquivado')], default='draft', max_length=20, verbose_name='Status')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'odt', 'rtf', 'jpg', 'jpeg', 'png', 'xlsx', 'xls', 'csv'])], verbose_name='Arquivo')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Tamanho (bytes)')),
                ('file_extension', models.CharField(blank=True, max_length=10, verbose_name='Extensão')),
                ('tags', models.CharField(blank=True, help_text='Tags separadas por vírgula', max_length=500, verbose_name='Tags')),
                ('is_confidential', models.BooleanField(default=False, verbose_name='Confidencial')),
                ('is_template', models.BooleanField(default=False, verbose_name='Modelo/Template')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Data do Documento')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_documents', to='customers.customer', verbose_name='Cliente')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='offices.office', verbose_name='Escritório')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organização')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='processes.process', verbose_name='Processo')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('comment', models.TextField(verbose_name='Comentário')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_comments', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='documents.document', verbose_name='Documento')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='offices.office', verbose_name='Escritório')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Pode Editar')),
                ('can_download', models.BooleanField(default=True, verbose_name='Pode Baixar')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('access_count', models.PositiveIntegerField(default=0, verbose_name='Acessos')),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True, verbose_name='Último acesso')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='documents.document', verbose_name='Documento')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='offices.office', verbose_name='Escritório')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organização')),
                ('shared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_shared_by_me', to=settings.AUTH_USER_MODEL, verbose_name='Compartilhado por')),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_documents', to=settings.AUTH_USER_MODEL, verbose_name='Compartilhado com')),
            ],
            options={
                'verbose_name': 'Compartilhamento',
                'verbose_name_plural': 'Compartilhamentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Versão')),
                ('file', models.FileField(upload_to='documents/versions/%Y/%m/', verbose_name='Arquivo')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Tamanho (bytes)')),
                ('changes_description', models.TextField(blank=True, verbose_name='Descrição das Alterações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_versions_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Versão do Documento',
                'verbose_name_plural': 'Versões do Documento',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Cor')),
                ('icon', models.CharField(default='fas fa-folder', max_length=50, verbose_name='Ícone')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folders_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='offices.office', verbose_name='Escritório')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organização')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='documents.folder', verbose_name='Pasta pai')),
            ],
            options={
                'verbose_name': 'Pasta',
                'verbose_name_plural': 'Pastas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Adicionado em')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_folder_adds', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_links', to='documents.document')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.folder')),
            ],
            options={
                'verbose_name': 'Documento na Pasta',
                'verbose_name_plural': 'Documentos nas Pastas',
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'office', 'title'], name='documents_d_organiz_ccce14_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'office', 'category'], name='documents_d_organiz_e7cc20_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'office', 'status'], name='documents_d_organiz_7cf4f7_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['process'], name='documents_d_process_0b1c2e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['customer'], name='documents_d_custome_28b801_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentshare',
            unique_together={('document', 'shared_with')},
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version_number')},
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('organization', 'office', 'name', 'parent')},
        ),
        migrations.AlterUniqueTogether(
            name='documentfolder',
            unique_together={('document', 'folder')},
        ),
    ]
