# Generated by Django 5.0.10 on 2026-02-24 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='offices.office', verbose_name='Escritório'),
        ),
    ]
