# Generated by Django 5.0.10 on 2026-02-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarentry',
            name='description',
            field=models.CharField(blank=True, max_length=120, verbose_name='Descrição curta'),
        ),
        migrations.AddField(
            model_name='calendarentry',
            name='required_fields',
            field=models.JSONField(blank=True, default=list, verbose_name='Campos obrigatórios'),
        ),
    ]
