# Generated by Django 5.0.10 on 2026-02-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_calendareventtemplate_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditentry',
            name='user',
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='AuditEntry',
        ),
    ]
