# Generated by Django 5.0.10 on 2026-02-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('org_admin', 'Admin da Organização'), ('office_admin', 'Admin do Escritório'), ('lawyer', 'Advogado'), ('staff', 'Equipe'), ('finance', 'Financeiro')], help_text='Label legado (não controla autorização).', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vínculo',
                'verbose_name_plural': 'Vínculos',
            },
        ),
        migrations.CreateModel(
            name='PermissionGroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_assignable_by_org_admin', models.BooleanField(default=True)),
                ('is_assignable_by_tech_director', models.BooleanField(default=True)),
                ('is_internal_only', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Perfil de Grupo de Permissão',
                'verbose_name_plural': 'Perfis de Grupos de Permissão',
                'ordering': ('sort_order', 'group__name'),
            },
        ),
        migrations.CreateModel(
            name='LocalRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='local_roles', to='auth.group')),
            ],
            options={
                'verbose_name': 'Função Local',
                'verbose_name_plural': 'Funções Locais',
                'ordering': ('name',),
            },
        ),
    ]
