# Generated by Django 5.0.10 on 2026-02-24 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memberships', '0001_initial'),
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localrole',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_roles', to='offices.office'),
        ),
    ]
