# Generated by Django 5.0.10 on 2026-02-24 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('memberships', '0002_initial'),
        ('offices', '0002_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='localrole',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_roles', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='membership',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='memberships', to='auth.group'),
        ),
        migrations.AddField(
            model_name='membership',
            name='local_role',
            field=models.ForeignKey(blank=True, help_text='Função local usada como preset de grupos (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='memberships.localrole'),
        ),
        migrations.AddField(
            model_name='membership',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='offices.office'),
        ),
        migrations.AddField(
            model_name='membership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permissiongroupprofile',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.group'),
        ),
        migrations.AddConstraint(
            model_name='localrole',
            constraint=models.UniqueConstraint(fields=('organization', 'office', 'name'), name='uniq_local_role_name_per_scope'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('office__isnull', False)), fields=('user', 'organization', 'office'), name='uniq_membership_user_org_office_nonnull'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('office__isnull', True)), fields=('user', 'organization'), name='uniq_membership_user_org_orglevel'),
        ),
    ]
