# Generated by Django 5.0.10 on 2026-02-24 13:49

import apps.processes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
        ('offices', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('number', models.CharField(help_text='Formato: NNNNNNN-DD.AAAA.J.TR.OOOO', max_length=40, validators=[apps.processes.models.validate_cnj], verbose_name='Número CNJ')),
                ('court', models.CharField(blank=True, max_length=255, verbose_name='Tribunal')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Assunto')),
                ('phase', models.CharField(blank=True, choices=[('initial', 'Inicial'), ('instruction', 'Instrução'), ('sentence', 'Sentença'), ('appeal', 'Recurso'), ('execution', 'Execução'), ('archived', 'Arquivado')], default='initial', max_length=100, verbose_name='Fase')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('suspended', 'Suspenso'), ('finished', 'Finalizado')], default='active', max_length=50, verbose_name='Status')),
                ('area', models.CharField(blank=True, choices=[('trabalhista', 'Trabalhista'), ('previdenciario', 'Previdenciário'), ('civil', 'Cível'), ('criminal', 'Criminal'), ('familia', 'Família'), ('tributario', 'Tributário'), ('empresarial', 'Empresarial'), ('consumidor', 'Consumidor'), ('administrativo', 'Administrativo'), ('outro', 'Outro')], max_length=50, verbose_name='Área Jurídica')),
                ('description', models.TextField(blank=True, verbose_name='Descrição / Objeto da Ação')),
                ('cause_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor da Causa (R$)')),
                ('filing_date', models.DateField(blank=True, null=True, verbose_name='Data de Ajuizamento')),
                ('distribution_date', models.DateField(blank=True, null=True, verbose_name='Data de Distribuição')),
                ('first_hearing_date', models.DateField(blank=True, null=True, verbose_name='Data da 1ª Audiência')),
                ('sentence_date', models.DateField(blank=True, null=True, verbose_name='Data da Sentença')),
                ('court_unit', models.CharField(blank=True, max_length=255, verbose_name='Vara / Unidade Judiciária')),
                ('judge_name', models.CharField(blank=True, max_length=255, verbose_name='Nome do Juiz')),
                ('risk', models.CharField(blank=True, choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto'), ('critico', 'Crítico')], max_length=20, verbose_name='Risco')),
                ('success_probability', models.PositiveSmallIntegerField(blank=True, help_text='0 a 100', null=True, verbose_name='Probabilidade de Êxito (%)')),
                ('tags', models.CharField(blank=True, help_text='Separadas por vírgula', max_length=500, verbose_name='Tags')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Observações Internas')),
                ('next_action', models.CharField(blank=True, max_length=500, verbose_name='Próxima Movimentação Esperada')),
                ('last_movement', models.CharField(blank=True, max_length=500, verbose_name='Última Movimentação')),
                ('last_movement_date', models.DateField(blank=True, null=True, verbose_name='Data da Última Movimentação')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='offices.office', verbose_name='Escritório')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organização')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
            },
        ),
        migrations.CreateModel(
            name='ProcessNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Texto')),
                ('is_private', models.BooleanField(default=True, verbose_name='Privada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_notes', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='processes.process')),
            ],
            options={
                'verbose_name': 'Nota do Processo',
                'verbose_name_plural': 'Notas do Processo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nome')),
                ('role', models.CharField(choices=[('autor', 'Autor'), ('reu', 'Réu'), ('terceiro', 'Terceiro'), ('advogado', 'Advogado'), ('testemunha', 'Testemunha'), ('perito', 'Perito'), ('outro', 'Outro')], max_length=20, verbose_name='Papel')),
                ('document', models.CharField(blank=True, max_length=50, verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefone')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_parties', to='customers.customer')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='processes.process')),
            ],
            options={
                'verbose_name': 'Parte do Processo',
                'verbose_name_plural': 'Partes do Processo',
            },
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['organization', 'office', 'number'], name='processes_p_organiz_cc9859_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='process',
            unique_together={('organization', 'office', 'number')},
        ),
    ]
