# Generated by Django 5.0.10 on 2026-02-22 12:53

import apps.organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('document', models.CharField(max_length=18, unique=True, validators=[apps.organizations.models.validate_cnpj], verbose_name='CNPJ')),
                ('plan', models.CharField(choices=[('basic', 'Básico'), ('pro', 'Profissional'), ('enterprise', 'Enterprise')], default='basic', max_length=20, verbose_name='Plano')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Configurações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Organização',
                'verbose_name_plural': 'Organizações',
                'ordering': ('-created_at',),
            },
        ),
    ]
