# Generated by Django 5.0.10 on 2026-02-26 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('offices', '0002_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgrole',
            options={'verbose_name': 'Função da Organização', 'verbose_name_plural': 'Funções da Organização'},
        ),
        migrations.AlterField(
            model_name='orgrole',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='org_roles', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='orgrole',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_roles', to='offices.office'),
        ),
        migrations.AlterField(
            model_name='orgrole',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_roles', to='organizations.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='orgrole',
            unique_together={('organization', 'office', 'name')},
        ),
    ]
